apiVersion: appconfiguration.azure.com/v20240601
kind: Snapshot
metadata:
  name: aso-sample-snapshot
  namespace: default
  annotations: 
    # Can't be directly deleted in Azure, only by deleting the parent database
    # We can delete it from the cluster by applying this annotation, but this won't change anything in Azure.
    serviceoperator.azure.com/reconcile-policy: detach-on-delete
spec:
  azureName: "snapshotv1"
  owner:
    name: aso-sample-confstore-v2
  compositionType: Key_Label
  filters:
  - key: "MyApp:Settings:*"
    label: "production"
  - key: "MyApp:Features:*" 
    label: "production"
  retentionPeriod: 2592000 # 30 days in seconds
  tags:
    Environment: "Production"
    Version: "v1.0.0"
    Purpose: "Backup"
